StreamIndexedIO/VDBObject : Avoid unnecessary copies
This placates Clang 12, which was emitting errors like the following :

```
src/IECore/StreamIndexedIO.cpp:395:18: error: loop variable 'it' of type 'const std::__1::pair<const std::__1::basic_string<char>, int>' creates a copy from type 'const std::__1::pair<const std::__1::basic_string<char>, int>' [-Werror,-Wrange-loop-analysis]
        for (const auto it : nameCodeMapping)
                        ^
src/IECore/StreamIndexedIO.cpp:395:7: note: use reference type 'const std::__1::pair<const std::__1::basic_string<char>, int> &' to prevent copying
        for (const auto it : nameCodeMapping)
             ^~~~~~~~~~~~~~~
                        &
1 error generated.
```