Canceller : Export symbols for Cancelled class
The symbol export was removed by the Windows compatibility work, but that broke the Gaffer unit tests on Mac, with errors like the following :

```
======================================================================
ERROR: testCancellation (GafferImageTest.MedianTest.MedianTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/john/dev/build/gaffer/python/GafferTest/TestCase.py", line 92, in __messageHandlerCleanup
    raise RuntimeError( "Unexpected message : " + mh.levelAsString( message.level ) + " : " + message.context + " : " + message.message )
RuntimeError: Unexpected message : ERROR : BackgroundTask : Traceback (most recent call last):
  File "/Users/john/dev/build/gaffer/python/GafferImageTest/MedianTest.py", line 154, in <lambda>
    bt = Gaffer.ParallelAlgo.callOnBackgroundThread( m["out"], lambda : GafferImageTest.processTiles( m["out"] ) )
RuntimeError: unidentifiable C++ exception
```