IECore init : Windows does not have ldopenflags
Traceback (most recent call last):
  File "M:\cortexBuild\bin\../bin/gaffer.py", line 56, in <module>
    import IECore
  File "M:\cortexBuild\python\IECore\__init__.py", line 51, in <module>
    __import__( "sys" ).setdlopenflags(
AttributeError: 'module' object has no attribute 'setdlopenflags'