SearchReplaceOp : Fix Python 3 encoding problems
We were getting these errors :

```
Traceback (most recent call last):
  File "/disk1/john/dev/cortex/test/IECore/SearchReplaceOp.py", line 75, in testSimple
    replaceWith = "en",
  File "/disk1/john/dev/cortex/python/IECore/OpOverwriting.py", line 60, in __opSmartOperator
    return self.operate( )
  File "/disk1/john/dev/cortex/python/IECore/SearchReplaceOp.py", line 120, in doOperation
    os.write( fd[0], outLine )
TypeError: a bytes-like object is required, not 'str'
```