DataAlgo : Fix compilation with Clang 12
Clang 12 emits this error :

```
src/IECore/DataAlgo.cpp:124:21: error: loop variable 't' is always a copy because the range of type 'const std::__1::vector<bool, std::__1::allocator<bool> >' does not return a reference [-Werror,-Wrange-loop-analysis]
                        for( const auto &t : data->readable() )
                                         ^
src/IECore/DataAlgo.cpp:98:10: note: in instantiation of function template specialization '(anonymous namespace)::UniqueValueCollector::uniqueValues<IECore::TypedData<std::__1::vector<bool, std::__1::allocator<bool> > > >' requested here
                return uniqueValues( data );
                       ^
src/IECore/DataAlgo.cpp:124:9: note: use non-reference type 'std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > >'
                        for( const auto &t : data->readable() )
                             ^~~~~~~~~~~~~~~
1 error generated.
```

What it is trying to say is that `vector<bool>` is an abomination, and returns proxies instead of references, and the proxy will be copied rather than bound to `const auto &`. One solution to this problem is to use a forwarding reference : `for( auto &&t : data->readable() )`. This works for all container types, but forces you to spend an hour or so wandering the internet to understand what it means and why it works. In this case we can instead remove all the manual iteration entirely by just constructing the container directly from a range.