ParameterBinding : Fix build on OSX
Using anonymous namespaces in a header doesn't really make sense, and led to this error from Clang :

include/IECorePython/ParameterBinding.inl:51:22: error: function 'valueValid2' is not needed and will not be emitted [-Werror,-Wunneeded-internal-declaration]

Additionally, defining `valueValid2` in the header led to duplicate symbol errors, so it is now defined in the .cpp file.