IECoreBinding : Simplify repr() for empty boxes
This works around the following error :

```
> eval( repr( imath.Box2f() )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 1, in <module>
OverflowError: bad numeric conversion: positive overflow
```

The problem occurred with both the Cortex and imath forms of the repr serialisation, and seems to be caused by imperfect round tripping for the FLT_MAX and FLT_MIN values used by an empty box. IECore uses `lexical_cast<string>( floatValue )` for this, and imath uses `stringstream << floatValue`, but both result in the exact same serialisation of "3.40282347e+38". This does provide accurate round tripping when parsed again as a float as follows :

```
const float f = FLT_MAX;
const string s = lexical_cast<string>( f );
const float f2 = lexical_cast<float>( s );
assert( f == f2 ); // OK!
```

But that's not what happens when we parse in Python, because python doesn't use floats - everything is a double instead. That puts us on a code path somewhat equivalent to this :

```
const float f = FLT_MAX;
const string s = lexical_cast<string>( f );
const double d = lexical_cast<double>( s ); // Equivalent to Python's parsing
const float f3 = numeric_cast<float>( d ); // Throws, because we're now a _tiny_ bit bigger than FLT_MAX
```

This problem didn't occur in the IECore bindings because we did a straight cast rather than using `numeric_cast`, and also doesn't occur in the imath bindings for Box3f (rather than Box2f) because Box3f doesn't use `numeric_cast` for some reason. It would be nice to fix the imath bindings to be consistent, but the chances of getting anything merged into the OpenEXR repo are almost nil at this point - PRs are just accumulating unanswered. Since the solution here also results in more readable serialisations, I think it's a decent enough work around.