IECoreUSD : force fromUSD to return boost::intrusive_ptr
On Windows (tested on MSVC 2017 and latest MSVC 2019 as of this commit), the compiler is not able to determine that "USDTypeTraits<T>::CortexVectorDataType" is a class and gives errors:
- cortex\contrib\IECoreUSD\include\IECoreUSD\DataAlgo.h(67): error C2510: 'CortexVectorDataType': left of '::' must be a class/struct/union
- cortex\contrib\IECoreUSD\include\IECoreUSD\DataAlgo.h(67): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
- cortex\contrib\IECoreUSD\include\IECoreUSD\DataAlgo.h(67): error C2061: syntax error: identifier 'fromUSD'
- cortex\contrib\IECoreUSD\include\IECoreUSD\DataAlgo.inl(145): error C2510: 'CortexVectorDataType': left of '::' must be a class/struct/union
- cortex\contrib\IECoreUSD\include\IECoreUSD\DataAlgo.inl(145): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
- cortex\contrib\IECoreUSD\include\IECoreUSD\DataAlgo.inl(145): error C2374: 'IECoreUSD::DataAlgo::Ptr': redefinition; multiple initialization
- cortex\contrib\IECoreUSD\include\IECoreUSD\DataAlgo.h(67): note: see declaration of 'IECoreUSD::DataAlgo::Ptr'
- cortex\contrib\IECoreUSD\include\IECoreUSD\DataAlgo.inl(145): error C2061: syntax error: identifier 'fromUSD'
- cortex\contrib\IECoreUSD\include\IECoreUSD\DataAlgo.inl(146): error C2143: syntax error: missing ';' before '{'
- cortex\contrib\IECoreUSD\include\IECoreUSD\DataAlgo.inl(146): error C2447: '{': missing function header (old-style formal list?)