PrimitiveVariable::IndexedView : Allow assignment
The default assignment operator could not be used because the `m_data` reference type prevented it, as GCC explains :

```
include/IECoreScene/PrimitiveVariable.h:118:26: error: non-static reference member 'const std::vector<Imath_2_2::Vec2<float> >& IECoreScene::PrimitiveVariable::IndexedView<Imath_2_2::Vec2<float> >::m_data', can't use default assignment operator
```

Storing `m_data` via pointer solves the problem.