IECoreImage module : Don't require IECore to be imported first
Without this, `import IECoreImage` results in this error :

```
  File "/Users/john/dev/build/gaffer/python/IECoreImage/__init__.py", line 35, in <module>
    from _IECoreImage import *
RuntimeError: extension class wrapper for base class IECore::Reader has not been created yet
```