Catch polymorphic exceptions by reference
This fixes this class of compilation error emitted by GCC 9 :

```
src/IECore/DateTimeData.cpp:87:22: error: catching polymorphic type 'const class boost::bad_lexical_cast' by value [-Werror=catch-value=]
   87 |  catch( const boost::bad_lexical_cast )
```

I don't think any of this is a real problem in these particular cases, because we weren't actually using the value in any way, so slicing during copy construction couldn't really hurt us.